spring.data.mongodb.uri=mongodb://localhost:27017/feedbackdb
spring.data.mongodb.database=feedbackdb
server.port=8081

#To make them false in production
springdoc.api-pdocs.enabled=true
springdoc.swagger-ui.enabled=true